const days = [
  { day: "01", title: "Первый закат на краю Африки", text: "Встречаем в аэропорту, заселяемся в Кейптауне и едем к океану. Вечером — ужин, вино и знакомство с маленькой компанией.", image: "day-1.webp" },
  { day: "02", title: "Кейптаун с высоты", text: "Летим на вертолёте над Атлантикой, гуляем по Bo-Kaap, слушаем африканские песни и встречаем закат на Camps Bay.", image: "day-2.webp" },
  { day: "03", title: "Вино и Столовая гора", text: "Дегустации и хороший обед среди виноградников. Вечером поднимаемся на главный символ города — за тем самым закатом.", image: "day-3.webp" },
  { day: "04", title: "На краю Африки", text: "Пингвины на Boulders Beach, мыс Доброй Надежды и финал дня у маяка Cape Point: вокруг только горы, океан и горизонт.", image: "day-4.webp" },
  { day: "05", title: "Контрасты Южной Африки", text: "Увидим жизнь тауншипа с местным гидом Тебекой, затем отправимся к весеннему цветению West Coast National Park.", image: "day-5.webp" },
  { day: "06", title: "Ночь в XVIII веке", text: "Устрицы в рыбацком Патерностере, историческая ферма, домашний ужин при свечах и ночь в усадьбе потомственного бура.", image: "day-6.webp" },
  { day: "07", title: "Сады и местная тусовка", text: "Гуляем по Babylonstoren, а вечером вливаемся в Первый четверг Стелленбоша: галереи, музыка, вино и город до ночи.", image: "day-7.webp" },
  { day: "08", title: "Большая пятёрка", text: "День африканской природы. Вместе с рейнджерами ищем львов, слонов, носорогов, буйволов и леопардов.", image: "day-8.webp" },
  { day: "09", title: "Киты, океан и дикий пляж", text: "Выходим в океан в Херманусе, попадаем на ежегодный фестиваль китов и завершаем день на диком Kogel Bay.", image: "day-9.webp" },
  { day: "10", title: "Последнее утро", text: "Заезжаем на винодельню Vergenoegd Löw, смотрим парад сотен уток — и только после этого едем в аэропорт.", image: "day-10.webp" },
];

const highlights = [
  ["Вертолёт", "Над Атлантикой и Кейптауном", "day-2.webp"], ["Киты", "Фестиваль бывает раз в году — и мы попадаем", "day-9.webp"],
  ["Сафари", "Ищем Великую африканскую пятёрку", "day-8.webp"], ["Край света", "Пингвины, Cape Point и мыс Доброй Надежды", "cape-point.webp"],
  ["Вино", "Винодельни, сады и гастрономия Кейпа", "day-3.webp"], ["Люди", "Тауншип с местным гидом и друзья в Стелленбоше", "day-5.webp"],
];
const stays = [
  ["Кейптаун", "25–29 сентября", "Distandt House by Neighbourgood", "stay-cape.webp"], ["Лангебаан", "29–30 сентября", "Langebaan Country Estate", "stay-langebaan.webp"],
  ["Kersefontein", "30 сентября – 1 октября", "Историческая усадьба XVIII века", "stay-farm.webp"], ["Стелленбош", "1–4 октября", "Life & Leisure Boutique Guesthouse", "stay-stellenbosch.webp"],
];
const included = ["Все трансферы и перемещения по маршруту", "Проживание и завтраки в отелях", "Ужин и завтрак на исторической ферме", "Полёт на вертолёте над Кейптауном", "Подъём на Столовую гору", "Сафари с профессиональным рейнджером", "Лодка для наблюдения за китами", "Тауншип с местным гидом", "Все входные билеты по программе", "Сопровождение турлидеров 24/7"];
const excluded = ["Авиабилеты до Кейптауна и обратно", "Обеды и ужины, кроме ужина на ферме", "Туристическая страховка", "Личные расходы"];

export default function Home() {
  return <main>
    <section className="hero"><div className="hero__photo" aria-hidden="true" /><header className="topbar"><img className="brand" src="/images/logo.png" alt="Пути путешествия" /><a className="topbar__link" href="#booking">Забронировать</a></header><div className="hero__content"><p className="eyebrow">25 сентября — 4 октября · 6 человек</p><h1>ЮАР — 10 дней<br />жизни на краю света</h1><p className="hero__lead">Кейптаун, океан, сафари, винодельни и люди, которые покажут страну изнутри.</p><a className="button" href="#route">Смотреть маршрут <span>↓</span></a></div><div className="hero__note">Авторский маршрут · Андрей + Настя</div></section>
    <section className="intro section-pad"><p className="section-kicker">Не тур по чек-листу</p><h2>Южная Африка,<br />которую проживают</h2><div className="intro__grid"><p className="big-copy">За десять дней мы увидим дикую природу, попробуем местную кухню и вино, познакомимся с разными сторонами Кейптауна и его людьми.</p><p>Мы выбрали эти даты не случайно. Помимо пингвинов и сафари, попадём на фестиваль китов, сезон весеннего цветения и Первый четверг — городской праздник, когда галереи, бары и улицы заполняются местными.</p></div><div className="intro__facts"><p><strong>10 дней</strong><span>от океана до саванны</span></p><p><strong>6 человек</strong><span>маленькая живая компания</span></p><p><strong>Всё готово</strong><span>маршрут, жильё и активности</span></p></div><div className="photo-pair"><figure><img src="/images/why.webp" alt="Кейптаун с высоты" /><figcaption>Кейптаун с высоты</figcaption></figure><figure><img src="/images/promise.webp" alt="Закат над побережьем Кейптауна" /><figcaption>Первый закат у Атлантики</figcaption></figure></div><p className="pullquote">Всё уже организовано. Вам останется только ловить впечатления.</p></section>
    <section className="hosts section-pad"><div className="hosts__photo"><img src="/images/hosts.webp" alt="Андрей и Настя — авторы путешествия" /></div><div className="hosts__copy"><p className="section-kicker">Кто мы</p><h2>Андрей<br />и Настя</h2><p className="big-copy">Историк и актриса, которые однажды уехали в Африку — и остались.</p><p>За прошлый сезон мы показали Южную Африку сотне путешественников и проехали по Кейпу около 40 000 км. Собрали маршрут из мест, которые любим сами: от главных видов до ресторанов, ферм и диких пляжей, куда редко добираются туристы.</p></div></section>
    <section className="highlights section-pad"><div className="section-head"><p className="section-kicker">Что ждёт</p><h2>Десять дней.<br />Очень много жизни.</h2></div><div className="highlights__rail">{highlights.map(([title,text,image],index)=><article className="highlight" key={title}><div className="highlight__image"><img src={`/images/${image}`} alt="" /></div><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="route" className="route section-pad"><div className="route__sticky"><p className="section-kicker">Маршрут</p><h2>10 дней<br />на краю земли</h2><p>Каждый день — новая Южная Африка. Программа может меняться местами из-за погоды, но не терять впечатления.</p></div><div className="days">{days.map(item=><article className="day" key={item.day}><img src={`/images/${item.image}`} alt="" /><div className="day__copy"><span>День {item.day}</span><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></section>
    <section className="stays section-pad"><div className="section-head"><p className="section-kicker">Где будем жить</p><h2>Четыре места.<br />Никаких случайных.</h2></div><div className="stays__grid">{stays.map(([city,dates,name,image])=><article className="stay" key={city}><img src={`/images/${image}`} alt={`${name}, ${city}`} /><div><p className="stay__date">{dates}</p><h3>{city}</h3><p>{name}</p></div></article>)}</div></section>
    <section className="details section-pad"><div className="details__top"><p className="section-kicker">Всё по-честному</p><h2>Что входит<br />в путешествие</h2></div><div className="lists"><div className="list-card list-card--included"><h3>Включено</h3>{included.map(x=><p key={x}><span>✓</span>{x}</p>)}</div><div className="list-card"><h3>Не входит</h3>{excluded.map(x=><p key={x}><span>×</span>{x}</p>)}</div></div></section>
    <section className="price section-pad"><p className="section-kicker">Стоимость</p><div className="price__grid"><div><p className="price__value">$2900</p><p>при бронировании от 2 мест</p></div><div><p className="price__value">$3200</p><p>для соло-путешественников</p></div></div><div className="price__meta"><p><strong>6 путешественников</strong><br />+ Андрей и Настя</p><p><strong>Депозит 50 000 ₽</strong><br />Остаток — в первый день тура</p></div><p className="price__small">−$100 для участников наших прошлых путешествий. Депозит фиксируется в долларовом эквиваленте и не возвращается при отмене менее чем за 30 дней.</p></section>
    <section className="info section-pad"><p className="section-kicker">Важно знать</p><h2>Без сюрпризов.<br />Кроме приятных.</h2><div className="info__grid"><article><span>01</span><h3>Погода</h3><p>Весна, обычно +18…+24 °C. Погода переменчивая, поэтому дни программы могут немного меняться местами.</p></article><article><span>02</span><h3>Безопасность</h3><p>Маршрут, транспорт и жильё подобраны с учётом безопасности. Группа всегда под нашим сопровождением.</p></article><article><span>03</span><h3>Если погода против</h3><p>Для вертолёта, океана или Столовой горы найдём равноценную активность либо вернём стоимость отменённой услуги.</p></article></div></section>
    <section className="faq section-pad"><p className="section-kicker">Частые вопросы</p><h2>Спросить — норм</h2><div className="faq__list"><details><summary>Нужна ли виза?<span>+</span></summary><p>Гражданам России виза в ЮАР не требуется.</p></details><details><summary>Нужны ли прививки?<span>+</span></summary><p>Для поездки в Кейптаун обязательные прививки не требуются.</p></details><details><summary>Можно ехать одному?<span>+</span></summary><p>Да. Многие приезжают без компании. Размещение — в двухместных номерах с раздельными кроватями.</p></details><details><summary>Сколько денег взять?<span>+</span></summary><p>От $500 обычно достаточно для обедов, ужинов и личных расходов.</p></details><details><summary>Что с авиабилетами?<span>+</span></summary><p>Мы поможем подобрать оптимальные рейсы под даты путешествия.</p></details></div></section>
    <section id="booking" className="booking section-pad"><div className="booking__image"><img src="/images/table-mountain.webp" alt="Столовая гора и Кейптаун" /></div><div className="booking__content"><p className="section-kicker">До встречи в Африке</p><h2>Полетели<br />на край света?</h2><p>Напишите Насте, подтвердите место и внесите депозит. С билетами поможем.</p><div className="booking__links"><a href="https://t.me/NastyaStarova" target="_blank" rel="noreferrer">Telegram <span>↗</span></a><a href="https://wa.me/27608328283" target="_blank" rel="noreferrer">WhatsApp <span>↗</span></a><a href="https://www.instagram.com/_nastyastar" target="_blank" rel="noreferrer">Instagram <span>↗</span></a><a href="https://vk.com/starovanastya" target="_blank" rel="noreferrer">ВКонтакте <span>↗</span></a></div></div></section>
    <a className="mobile-cta" href="#booking"><span>Осталось 6 мест</span><strong>Забронировать →</strong></a>
  </main>;
}
